# Generated by Django 6.1 on 2026-08-31 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evidence', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='título')),
                ('autores_texto', models.TextField(help_text='Lista de autores en formato APA o IEEE', verbose_name='autores')),
                ('tipo', models.CharField(choices=[('ARTICULO_JCR', 'Artículo JCR / Scopus'), ('ARTICULO_CONACYT', 'Artículo Conacyt / Índice Nacional'), ('CAPITULO_LIBRO', 'Capítulo de Libro'), ('OTRO', 'Otro')], max_length=30, verbose_name='tipo de publicación')),
                ('revista_editorial', models.CharField(max_length=255, verbose_name='revista o editorial')),
                ('estado', models.CharField(choices=[('PREPARACION', 'En Preparación'), ('ENVIADO', 'Enviado'), ('EN_REVISION', 'En Revisión'), ('ACEPTADO', 'Aceptado'), ('PUBLICADO', 'Publicado')], default='PREPARACION', max_length=30, verbose_name='estado')),
                ('fecha_publicacion', models.DateField(blank=True, db_index=True, null=True, verbose_name='fecha de publicación')),
                ('doi_url', models.CharField(blank=True, default='', max_length=500, verbose_name='DOI o URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('evidencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='evidence.evidence', verbose_name='evidencia')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='students.semester', verbose_name='semestre')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='students.student', verbose_name='estudiante')),
            ],
            options={
                'verbose_name': 'publicación',
                'verbose_name_plural': 'publicaciones',
                'ordering': ['-fecha_publicacion', '-created_at'],
            },
        ),
    ]
