# Generated by Django 6.1 on 2026-08-31 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_output', '0001_initial'),
        ('evidence', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('CONGRESO_NACIONAL', 'Congreso Nacional'), ('CONGRESO_INTERNACIONAL', 'Congreso Internacional'), ('COLOQUIO', 'Coloquio / Simposio')], max_length=40, verbose_name='tipo de evento')),
                ('nombre_evento', models.CharField(max_length=255, verbose_name='nombre del evento')),
                ('titulo_ponencia', models.CharField(max_length=255, verbose_name='título de la ponencia')),
                ('fecha_presentacion', models.DateField(db_index=True, verbose_name='fecha de presentación')),
                ('sede_lugar', models.CharField(max_length=255, verbose_name='sede o lugar')),
                ('modalidad', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('VIRTUAL', 'Virtual'), ('HIBRIDA', 'Híbrida')], default='PRESENCIAL', max_length=20, verbose_name='modalidad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('evidencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_events', to='evidence.evidence', verbose_name='evidencia')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_events', to='students.semester', verbose_name='semestre')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_events', to='students.student', verbose_name='estudiante')),
            ],
            options={
                'verbose_name': 'evento académico',
                'verbose_name_plural': 'eventos académicos',
                'ordering': ['-fecha_presentacion', '-created_at'],
            },
        ),
    ]
