# Generated by Django 6.1 on 2026-08-31 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_output', '0002_academicevent'),
        ('evidence', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchStay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion_receptora', models.CharField(max_length=255, verbose_name='institución receptora')),
                ('pais', models.CharField(max_length=100, verbose_name='país')),
                ('fecha_inicio', models.DateField(db_index=True, verbose_name='fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='fecha de finalización')),
                ('responsable_estancia', models.CharField(max_length=255, verbose_name='responsable / investigador anfitrión')),
                ('objetivos', models.TextField(blank=True, default='', verbose_name='objetivos de la estancia')),
                ('resultados', models.TextField(blank=True, default='', verbose_name='resultados obtenidos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('evidencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_stays', to='evidence.evidence', verbose_name='evidencia')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_stays', to='students.student', verbose_name='estudiante')),
            ],
            options={
                'verbose_name': 'estancia de investigación',
                'verbose_name_plural': 'estancias de investigación',
                'ordering': ['-fecha_inicio', '-created_at'],
            },
        ),
    ]
