# Generated by Django 6.1 on 2026-08-31 23:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_output', '0003_researchstay'),
        ('evidence', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_producto', models.CharField(choices=[('SOFTWARE', 'Desarrollo de Software'), ('PROTOTIPO', 'Prototipo Físico / Industrial'), ('PATENTE', 'Propiedad Intelectual / Patente'), ('BASE_DATOS', 'Base de Datos de Investigación'), ('OTRO', 'Otro')], max_length=30, verbose_name='tipo de producto')),
                ('titulo', models.CharField(max_length=255, verbose_name='título del producto')),
                ('descripcion', models.TextField(verbose_name='descripción y características')),
                ('fecha_registro', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='fecha de registro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('evidencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_products', to='evidence.evidence', verbose_name='evidencia')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_products', to='students.student', verbose_name='estudiante')),
            ],
            options={
                'verbose_name': 'otro producto académico',
                'verbose_name_plural': 'otros productos académicos',
                'ordering': ['-fecha_registro', '-created_at'],
            },
        ),
    ]
