# Generated by Django 6.1 on 2026-08-31 22:44

import apps.thesis.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThesisProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_avance', models.PositiveSmallIntegerField(help_text='Porcentaje global de avance de la tesis (0-100%)', validators=[django.core.validators.MinValueValidator(0, message='El porcentaje no puede ser menor a 0%'), django.core.validators.MaxValueValidator(100, message='El porcentaje no puede ser mayor a 100%')], verbose_name='porcentaje de avance')),
                ('componentes_json', models.JSONField(blank=True, default=apps.thesis.models.default_thesis_components, help_text='Desglose de avance por componentes clave del proyecto doctoral', verbose_name='componentes de tesis')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='observaciones')),
                ('fecha_registro', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='fecha de registro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thesis_progresses', to='students.semester', verbose_name='semestre')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thesis_progresses', to='students.student', verbose_name='estudiante')),
            ],
            options={
                'verbose_name': 'avance de tesis',
                'verbose_name_plural': 'avances de tesis',
                'ordering': ['-fecha_registro', '-created_at'],
            },
        ),
    ]
