# Generated by Django 6.1 on 2026-08-31 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutoringSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_sesion', models.DateField(db_index=True, verbose_name='fecha de la sesión')),
                ('modalidad', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('VIRTUAL', 'Virtual'), ('HIBRIDA', 'Híbrida')], default='PRESENCIAL', max_length=20, verbose_name='modalidad')),
                ('resumen', models.TextField(verbose_name='resumen de la sesión')),
                ('proxima_reunion_fecha', models.DateField(blank=True, null=True, verbose_name='fecha de próxima reunión')),
                ('proxima_reunion_notas', models.TextField(blank=True, default='', verbose_name='notas de próxima reunión')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_tutoring_sessions', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutoring_sessions', to='students.semester', verbose_name='semestre')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutoring_sessions', to='students.student', verbose_name='estudiante')),
            ],
            options={
                'verbose_name': 'sesión de tutoría',
                'verbose_name_plural': 'sesiones de tutoría',
                'ordering': ['-fecha_sesion', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TutoringObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_tema', models.CharField(max_length=255, verbose_name='título o tema revisado')),
                ('contenido', models.TextField(verbose_name='contenido / comentarios de avance')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de registro')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutoring_observations', to=settings.AUTH_USER_MODEL, verbose_name='autor de la observación')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='tutoring.tutoringsession', verbose_name='sesión de tutoría')),
            ],
            options={
                'verbose_name': 'observación de tutoría',
                'verbose_name_plural': 'observaciones de tutoría',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TutoringParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_en_sesion', models.CharField(choices=[('ESTUDIANTE', 'Estudiante'), ('ASESOR_PRINCIPAL', 'Asesor Principal'), ('COASESOR', 'Coasesor'), ('VOCAL', 'Vocal'), ('SECRETARIO', 'Secretario'), ('INVITADO', 'Invitado')], max_length=30, verbose_name='rol en la sesión')),
                ('asistencia', models.BooleanField(default=True, verbose_name='asistencia')),
                ('notas', models.CharField(blank=True, default='', max_length=255, verbose_name='notas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutoring_attendances', to=settings.AUTH_USER_MODEL, verbose_name='usuario participante')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tutoring.tutoringsession', verbose_name='sesión de tutoría')),
            ],
            options={
                'verbose_name': 'participante de tutoría',
                'verbose_name_plural': 'participantes de tutoría',
                'ordering': ['rol_en_sesion', 'user'],
                'constraints': [models.UniqueConstraint(fields=('session', 'user'), name='unique_session_participant')],
            },
        ),
    ]
