# Generated by Django 6.1 on 2026-08-31 22:45

import apps.evidence.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ARCHIVO_LOCAL', 'Archivo Local'), ('ENLACE_DOI', 'Enlace DOI/URL')], db_index=True, default='ARCHIVO_LOCAL', max_length=20, verbose_name='tipo de evidencia')),
                ('actividad_tipo', models.CharField(choices=[('TUTORIA', 'Tutoría'), ('ACUERDO', 'Acuerdo'), ('TESIS', 'Avance de Tesis'), ('OTRO', 'Otro')], db_index=True, default='OTRO', max_length=20, verbose_name='tipo de actividad vinculada')),
                ('actividad_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='ID de actividad vinculada')),
                ('titulo', models.CharField(max_length=255, verbose_name='título de la evidencia')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='descripción')),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='evidence/%Y/%m/', validators=[apps.evidence.models.validate_evidence_file], verbose_name='archivo adjunto')),
                ('enlace_url', models.CharField(blank=True, default='', max_length=500, verbose_name='enlace o DOI')),
                ('mime_type', models.CharField(blank=True, default='', max_length=100, verbose_name='tipo MIME')),
                ('file_size_bytes', models.BigIntegerField(default=0, verbose_name='tamaño en bytes')),
                ('fecha_carga', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='fecha de carga')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_evidences', to=settings.AUTH_USER_MODEL, verbose_name='cargado por')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidences', to='students.semester', verbose_name='semestre')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='students.student', verbose_name='estudiante')),
            ],
            options={
                'verbose_name': 'evidencia',
                'verbose_name_plural': 'evidencias',
                'ordering': ['-fecha_carga', '-created_at'],
            },
        ),
    ]
