# Generated by Django 6.1 on 2026-08-31 22:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='matrícula')),
                ('nombre_completo', models.CharField(max_length=255, verbose_name='nombre completo')),
                ('programa_doctoral', models.CharField(default='Doctorado en Ciencias', max_length=255, verbose_name='programa doctoral')),
                ('cohorte', models.CharField(max_length=20, verbose_name='cohorte')),
                ('estatus_activo', models.BooleanField(default=True, verbose_name='estatus activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'estudiante',
                'verbose_name_plural': 'estudiantes',
                'ordering': ['matricula'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='El semestre no puede ser menor a 1'), django.core.validators.MaxValueValidator(6, message='El semestre no puede ser mayor a 6')], verbose_name='número de semestre')),
                ('fecha_inicio', models.DateField(verbose_name='fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='fecha de fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='students.student')),
            ],
            options={
                'verbose_name': 'semestre',
                'verbose_name_plural': 'semestres',
                'ordering': ['numero'],
                'constraints': [models.UniqueConstraint(fields=('student', 'numero'), name='unique_student_semester')],
            },
        ),
        migrations.CreateModel(
            name='AcademicCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_comite', models.CharField(choices=[('ASESOR_PRINCIPAL', 'Asesor Principal / Director'), ('COASESOR', 'Coasesor'), ('VOCAL', 'Vocal'), ('SECRETARIO', 'Secretario')], default='ASESOR_PRINCIPAL', max_length=30, verbose_name='rol en el comité')),
                ('fecha_asignacion', models.DateField(default=django.utils.timezone.now, verbose_name='fecha de asignación')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_assignments', to=settings.AUTH_USER_MODEL, verbose_name='usuario académico')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_members', to='students.student', verbose_name='estudiante')),
            ],
            options={
                'verbose_name': 'miembro de comité académico',
                'verbose_name_plural': 'miembros de comité académico',
                'ordering': ['-is_active', 'rol_comite', '-fecha_asignacion'],
                'constraints': [models.UniqueConstraint(fields=('student', 'user', 'rol_comite'), name='unique_student_user_committee_role')],
            },
        ),
    ]
